/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'playType' : PlayType,
  'number' : string,
  'timestamp' : Time,
  'gameType' : GameType,
  'amount' : bigint,
}
export interface Booking {
  'userName' : string,
  'playType' : PlayType,
  'bookingDate' : string,
  'timestamp' : Time,
  'contactNumber' : string,
  'gameType' : GameType,
}
export type GameType = { 'thailandLottery' : null } |
  { 'bangkokWeekly' : null };
export type PlayType = { 'vip' : null } |
  { 'rumble' : null } |
  { 'local' : null };
export interface Result {
  'winningNumber' : string,
  'date' : string,
  'time' : string,
  'gameName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllResults' : ActorMethod<[], Array<Result>>,
  'getBangkokHistory' : ActorMethod<[], Array<Result>>,
  'getBets' : ActorMethod<[], Array<Bet>>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getResultByDate' : ActorMethod<[string], Result>,
  'getThaiHistory' : ActorMethod<[], Array<Result>>,
  'init' : ActorMethod<[], undefined>,
  'submitBet' : ActorMethod<[string, bigint, PlayType, GameType], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, GameType, PlayType, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];