/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Record({
  'winningNumber' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'gameName' : IDL.Text,
});
export const PlayType = IDL.Variant({
  'vip' : IDL.Null,
  'rumble' : IDL.Null,
  'local' : IDL.Null,
});
export const Time = IDL.Int;
export const GameType = IDL.Variant({
  'thailandLottery' : IDL.Null,
  'bangkokWeekly' : IDL.Null,
});
export const Bet = IDL.Record({
  'playType' : PlayType,
  'number' : IDL.Text,
  'timestamp' : Time,
  'gameType' : GameType,
  'amount' : IDL.Nat,
});
export const Booking = IDL.Record({
  'userName' : IDL.Text,
  'playType' : PlayType,
  'bookingDate' : IDL.Text,
  'timestamp' : Time,
  'contactNumber' : IDL.Text,
  'gameType' : GameType,
});

export const idlService = IDL.Service({
  'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getBangkokHistory' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'getBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getResultByDate' : IDL.Func([IDL.Text], [Result], ['query']),
  'getThaiHistory' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'init' : IDL.Func([], [], []),
  'submitBet' : IDL.Func([IDL.Text, IDL.Nat, PlayType, GameType], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, GameType, PlayType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Record({
    'winningNumber' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'gameName' : IDL.Text,
  });
  const PlayType = IDL.Variant({
    'vip' : IDL.Null,
    'rumble' : IDL.Null,
    'local' : IDL.Null,
  });
  const Time = IDL.Int;
  const GameType = IDL.Variant({
    'thailandLottery' : IDL.Null,
    'bangkokWeekly' : IDL.Null,
  });
  const Bet = IDL.Record({
    'playType' : PlayType,
    'number' : IDL.Text,
    'timestamp' : Time,
    'gameType' : GameType,
    'amount' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'userName' : IDL.Text,
    'playType' : PlayType,
    'bookingDate' : IDL.Text,
    'timestamp' : Time,
    'contactNumber' : IDL.Text,
    'gameType' : GameType,
  });
  
  return IDL.Service({
    'getAllResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getBangkokHistory' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'getBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getResultByDate' : IDL.Func([IDL.Text], [Result], ['query']),
    'getThaiHistory' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'init' : IDL.Func([], [], []),
    'submitBet' : IDL.Func([IDL.Text, IDL.Nat, PlayType, GameType], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, GameType, PlayType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };