/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Booking {
    userName: string;
    playType: PlayType;
    bookingDate: string;
    timestamp: Time;
    contactNumber: string;
    gameType: GameType;
}
export interface Result {
    winningNumber: string;
    date: string;
    time: string;
    gameName: string;
}
export type Time = bigint;
export interface Bet {
    playType: PlayType;
    number: string;
    timestamp: Time;
    gameType: GameType;
    amount: bigint;
}
export enum GameType {
    thailandLottery = "thailandLottery",
    bangkokWeekly = "bangkokWeekly"
}
export enum PlayType {
    vip = "vip",
    rumble = "rumble",
    local = "local"
}
export interface backendInterface {
    getAllResults(): Promise<Array<Result>>;
    getBangkokHistory(): Promise<Array<Result>>;
    getBets(): Promise<Array<Bet>>;
    getBookings(): Promise<Array<Booking>>;
    getResultByDate(date: string): Promise<Result>;
    getThaiHistory(): Promise<Array<Result>>;
    init(): Promise<void>;
    submitBet(number: string, amount: bigint, playType: PlayType, gameType: GameType): Promise<void>;
    submitBooking(userName: string, contactNumber: string, gameType: GameType, playType: PlayType, bookingDate: string): Promise<void>;
}
import type { Bet as _Bet, Booking as _Booking, GameType as _GameType, PlayType as _PlayType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllResults(): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResults();
            return result;
        }
    }
    async getBangkokHistory(): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBangkokHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBangkokHistory();
            return result;
        }
    }
    async getBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBets();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBets();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultByDate(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultByDate(arg0);
            return result;
        }
    }
    async getThaiHistory(): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThaiHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThaiHistory();
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async submitBet(arg0: string, arg1: bigint, arg2: PlayType, arg3: GameType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBet(arg0, arg1, to_candid_PlayType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_GameType_n13(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBet(arg0, arg1, to_candid_PlayType_n11(this._uploadFile, this._downloadFile, arg2), to_candid_GameType_n13(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: GameType, arg3: PlayType, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, to_candid_GameType_n13(this._uploadFile, this._downloadFile, arg2), to_candid_PlayType_n11(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, to_candid_GameType_n13(this._uploadFile, this._downloadFile, arg2), to_candid_PlayType_n11(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Bet_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bet): Bet {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_GameType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameType): GameType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PlayType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayType): PlayType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userName: string;
    playType: _PlayType;
    bookingDate: string;
    timestamp: _Time;
    contactNumber: string;
    gameType: _GameType;
}): {
    userName: string;
    playType: PlayType;
    bookingDate: string;
    timestamp: Time;
    contactNumber: string;
    gameType: GameType;
} {
    return {
        userName: value.userName,
        playType: from_candid_PlayType_n4(_uploadFile, _downloadFile, value.playType),
        bookingDate: value.bookingDate,
        timestamp: value.timestamp,
        contactNumber: value.contactNumber,
        gameType: from_candid_GameType_n6(_uploadFile, _downloadFile, value.gameType)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playType: _PlayType;
    number: string;
    timestamp: _Time;
    gameType: _GameType;
    amount: bigint;
}): {
    playType: PlayType;
    number: string;
    timestamp: Time;
    gameType: GameType;
    amount: bigint;
} {
    return {
        playType: from_candid_PlayType_n4(_uploadFile, _downloadFile, value.playType),
        number: value.number,
        timestamp: value.timestamp,
        gameType: from_candid_GameType_n6(_uploadFile, _downloadFile, value.gameType),
        amount: value.amount
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vip: null;
} | {
    rumble: null;
} | {
    local: null;
}): PlayType {
    return "vip" in value ? PlayType.vip : "rumble" in value ? PlayType.rumble : "local" in value ? PlayType.local : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thailandLottery: null;
} | {
    bangkokWeekly: null;
}): GameType {
    return "thailandLottery" in value ? GameType.thailandLottery : "bangkokWeekly" in value ? GameType.bangkokWeekly : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bet>): Array<Bet> {
    return value.map((x)=>from_candid_Bet_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n9(_uploadFile, _downloadFile, x));
}
function to_candid_GameType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): _GameType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PlayType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayType): _PlayType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayType): {
    vip: null;
} | {
    rumble: null;
} | {
    local: null;
} {
    return value == PlayType.vip ? {
        vip: null
    } : value == PlayType.rumble ? {
        rumble: null
    } : value == PlayType.local ? {
        local: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameType): {
    thailandLottery: null;
} | {
    bangkokWeekly: null;
} {
    return value == GameType.thailandLottery ? {
        thailandLottery: null
    } : value == GameType.bangkokWeekly ? {
        bangkokWeekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
